name: Check Menu Email

on:
  schedule:
    - cron: '0 7 * * 6'
  workflow_dispatch:

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Esegui lo script di scaricamento
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python download_menu.py

      # --- NUOVO PASSAGGIO: Salva i file scaricati nel repository ---
      - name: Commit e Push dei file scaricati
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/
          # Esegue il commit solo se ci sono effettivamente nuovi file scaricati
          git diff-index --quiet HEAD || (git commit -m "💾 Aggiunto nuovo allegato menù" && git push)
